feishu:
  enabled: true
  appId: "cli_a944ebad32b99cb0"
  appSecret:
    source: "file"
    provider: "lark-secrets"
    id: "/lark/appSecret"
  domain: "feishu"
  connectionMode: "websocket"
  requireMention: true
  dmPolicy: "open"
  allowFrom:
    - "ou_b000e94d42b8d11685eab27e26237f32"
  groupAllowFrom:
    - "ou_b000e94d42b8d11685eab27e26237f32"
    - "oc_db02140c3408a641f366dffc0638fb3e"
  groupPolicy: "open"
  groups:
    "*":
      enabled: true

llm:
  provider: "glm"
  api_key: "YOUR_API_KEY"
  model: "glm-4"

skills:
  dir: "."

agent:
  name: "陈皮"

logging:
  level: "INFO"
  file: "./logs/coleague.log"
